#!/bin/csh -f
if ($#argv != 6) then
  echo "Usage: mpirun_anag exec inputs threads procs mach iter"
  exit 1
endif

set exec    = $1
set inputs  = $2
set threads = $3
set procs   = $4
set mach    = $5
set maxIter = $6
    
echo "executable name   = $exec"
echo "input file name   = $inputs"
echo "number of procs   = $procs"
echo "number of threads = $threads"
echo "machine file      = $mach " 
set iter  = 0

while ($iter <= $maxIter)

echo "iteration = $iter"

set command =     "setenv OMP_NUM_THREADS $threads"
echo $command
$command

set command = "mpirun -machinefile $mach -np $procs $exec $inputs"
echo $command
$command

set command = "cat pout.0"
echo $command
$command

set iter = `expr $iter + 1`
end
