# -*- Mode: Makefile -*- 

## Define the variables needed by Make.example

# trace the chain of included makefiles
makefiles += test_multiDim

# in an example of true silliness, need to define ebase so that the 
# realclean target will also remove my *.ex files...
ebase = bogus

# the location of Chombo lib dir
CHOMBO_HOME = ../../

# names of Chombo libraries needed by this program, in order of search.
1dLibNames = OldAMRElliptic AMRTools BoxTools BaseTools
2dLibNames = AMRTools BoxTools
3dLibNames = BoxTools
#4dLibNames = BoxTools
#5dLibNames = BoxTools
#6dLibNames = BoxTools

#LibNames =  OldAMRElliptic  AMRTools  BoxTools

# relative paths to source code directories
base_dir = .
1dsrc_dirs = 
2dsrc_dirs = 
3dsrc_dirs = 
mdsrc_dirs = 

# input file for 'run' target
INPUT = regression.inputs

# shared code for building example programs
include $(CHOMBO_HOME)/mk/Make.example.multidim

# application-specific variables

# application-specific targets

