# Makefile for the Magnetohydrodynamics (MHD) Module 

VPATH += $(SRC)/MHD/CT
OBJ   += ct_field_average.o ct_emf.o ct_emf_average.o emf_boundary.o 
OBJ   += emf_userdef.o ct.o ct_fill_mag_field.o ct_stag_slopes.o
HEADERS += ct.h
 

