#!/bin/csh -f

###
### Purpose: print the argument list in reverse order
###

if ( $#argv < 1 ) then
    exit 0
endif

set noglob

echo -n "${argv[$#argv]:q}"

@ i = $#argv - 1

while ( $i > 0 )
    echo -n " ${argv[$i]:q}"
    @ i = $i - 1
end

echo ""

