# Makefile for the relativistic MHD Module 

VPATH += $(SRC)/RMHD
INCLUDE_DIRS += -I$(SRC)/RMHD
OBJ   +=  eigenv.o energy_solve.o entropy_solve.o \
          four_vel.o fluxes.o gmusta1.o \
          mappers.o pressure_fix.o tvdlf.o  \
          hll_speed.o hll.o hllc.o hlld.o rhs.o \
          set_solver.o source.o vel_limiter.o 
 
