# **********************************************************************
#  Makefile for the resistivity module 
# **********************************************************************

VPATH   += $(SRC)/MHD/Resistivity
OBJ     += res_flux.o res_eta.o res_functions.o 
HEADERS += res.h
 

