# -*- Mode: Makefile -*- 

### This makefile produces a library for the name in the 'lbase' variable
### depending on the libraries named in the 'LibNames' variable

# included makefiles need an absolute path
CHOMBO_HOME := $(shell pwd)/../..

lbase := amrtimedependent

LibNames := AMRTools BoxTools

include $(CHOMBO_HOME)/mk/Make.lib
