# Makefile for the ArrayLib 

VPATH += $(PLUTO_DIR)/Src/Parallel
OBJ += al_alloc.o al_boundary.o al_decompose.o al_exchange.o \
       al_exchange_dim.o al_finalize.o al_init.o al_io.o al_sort_.o al_subarray_.o \
       al_sz_free.o al_sz_get.o al_sz_init.o al_szptr_.o al_sz_set.o  al_decomp_.o \
       al_write_array_async.o
HEADERS += al_codes.h  al_defs.h  al.h  al_hidden.h  al_proto.h

