# Makefile for the Magnetohydrodynamics (MHD) Module 

VPATH        +=  $(SRC)/MHD
INCLUDE_DIRS += -I$(SRC)/MHD
OBJ   +=  bckgrnd_field.o eigenv.o fluxes.o get_current.o \
          hll.o hllc.o hlld.o hll_speed.o mappers.o  prim_eqn.o \
          rhs.o roe.o set_solver.o source.o tvdlf.o

OBJ += rhs_source.o


