# Makefile for the Magnetohydrodynamics (MHD) Module 

VPATH        +=  $(SRC)/MHD
INCLUDE_DIRS += -I$(SRC)/MHD
OBJ   +=  bckgrnd_field.o eigenv.o fluxes.o mappers.o  prim_eqn.o \
          hll.o hllc.o hlld.o hll_speed.o rhs.o roe.o tvdlf.o \
          set_solver.o source.o


# !!! NEW !!!

OBJ += get_area_flux.o rhs_source.o


