# Makefile for PVTE_LAW EOS

VPATH   += $(SRC)/EOS/PVTE
INCLUDE_DIRS += -I$(SRC)/EOS/PVTE
OBJ     += fundamental_derivative.o pvte_law.o zeta_tables.o
OBJ     += thermal_eos.o internal_energy.o 
HEADERS += eos.h
