#!/bin/csh -f
if ($#argv != 3) then
  echo "Usage: omprun_anag exec inputs threads"
  exit 1
endif

set exec    = $1
set inputs  = $2
set procs = $3
echo "executable name = $exec"
echo "input file name = $inputs"

echo "number of threads = $procs"
set command =     "setenv OMP_NUM_THREADS $procs"
echo $command
$command

set command = "$exec $inputs"
echo $command
$command

