# Makefile for the Math_Tools module

VPATH   += $(SRC)/Math_Tools
OBJ     += math_interp.o \
           math_lu_decomp.o \
           math_qr_decomp.o \
           math_misc.o \
           math_ode.o \
           math_quadrature.o \
           math_root_finders.o \
           math_table2D.o 
HEADERS += math_tools.h
