#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _MASKVAL_H_
#define _MASKVAL_H_

#if 0
These mask value definitions should correspond with those in LevelMask.H
They are intended for use in FORTRAN routines
#endif

#define MASKCOVERED  -2
#define MASKPHYS     -1
#define MASKCOPY      0
#define MASKCOARSE    1

#endif
