#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _EBADVECTMACROS_H_
#define _EBADVECTMACROS_H_

#define PSCALAR  0
#define CNUM     1
#define QNUM     1
#define QSLOPE   1
#define FNUM     1

#endif
