#!/bin/sh

echo "//////////////////////////////////////////////////////////////////////////"
echo "// Do not hand-edit this file.  It was generated by                     //"
echo "// lib/util/multidim/make_FortranNameMacro_H.sh, which was called in    //"
echo "// turn by BoxTools/Makefile.                                           //"
echo "//////////////////////////////////////////////////////////////////////////"

printBasicStuff() {
  if test $# -eq 1; then
      Xd=" ## ${1}"
      Xd_=" ## ${1}_"
  else
      Xd=
      Xd_=
  fi

  indentation="      "
  echo "${indentation}#ifdef CH_FORT_UPPERCASE"
  echo "${indentation}  #ifdef CH_FORT_UNDERSCORE"
  echo "${indentation}     #define FORTRAN_NAME( NAME ,name ) NAME ## _ $Xd_"
  echo "${indentation}  #else"
  echo "${indentation}     #define FORTRAN_NAME( NAME ,name ) NAME $Xd"
  echo "${indentation}  #endif"
  echo "${indentation}#else"
  echo "${indentation}  #ifdef CH_FORT_UNDERSCORE"
  echo "${indentation}     #define FORTRAN_NAME( NAME ,name ) name ## _ $Xd_"
  echo "${indentation}  #else"
  echo "${indentation}     #define FORTRAN_NAME( NAME ,name ) name $Xd"
  echo "${indentation}  #endif"
  echo "${indentation}#endif"
}

includeguard=LAST_MULTIDIM_FortranNameMacro_SPACEDIM

echo "#ifndef CH_MULTIDIM"
printBasicStuff
echo "#else"
echo "  #ifndef $includeguard"
echo "    #define $includeguard 0"
echo "  #endif"
echo "  #if CH_SPACEDIM != $includeguard"
echo "    #undef $includeguard"
echo "    #ifdef FORTRAN_NAME"
echo "      #undef FORTRAN_NAME"
echo "    #endif"
echo "    #if   CH_SPACEDIM == 0"

max_dim=3
dim=1
while test $dim -le $max_dim ; do
    Xd=${dim}d
    echo "    #elif CH_SPACEDIM == $dim"
    printBasicStuff $Xd
    echo "      #define $includeguard $dim"
    dim=`expr $dim + 1`
done
echo "    #endif"


echo "  #endif"
echo "#endif"
