# Add objects file for Particles module 

VPATH        += $(SRC)/Particles
INCLUDE_DIRS += -I$(SRC)/Particles

OBJ += particles_boundary.o particles_deposit.o particles_init.o particles_set.o
OBJ +=  particles_restart.o particles_tools.o plist_tools.o  
OBJ += particles_mpi_datatype.o
OBJ +=  particles_set_output.o
OBJ +=  particles_write_bin.o particles_write_data.o particles_write_trajectory.o particles_write_vtk.o 
OBJ +=  particles_load.o 
OBJ +=  particles_cr_feedback.o   particles_cr_force.o  particles_cr_update.o particles_cr_update_test.o
#OBJ +=  particles_dust_feedback.o particles_dust_force.o particles_dust_update.o 
OBJ +=  particles_lp_tools.o particles_lp_update.o 
#OBJ +=  particles_lp_emissivity.o particles_lp_spectra.o  


HEADERS += particles.h






