# the location of Chombo lib dir
CHOMBO_HOME = ../../../lib

include $(CHOMBO_HOME)/mk/Make.defs
include $(CHOMBO_HOME)/mk/Make.defs.config
include $(CHOMBO_HOME)/mk/Make.example.multidim

regression:
	rm -f $(mdebase)$(config).ex
	ln -s $(mdebase).$(newconfig).ex $(mdebase)$(config).ex
