# Makefile for SNEq sources   

VPATH        += $(SRC)/Cooling/SNEq
INCLUDE_DIRS += -I$(SRC)/Cooling/SNEq

COOL_OBJ = jacobian.o maxrate.o radiat.o
OBJ     += $(COOL_OBJ)
HEADERS += cooling.h

$(COOL_OBJ):  $(HEADERS)
 

